name: repo_update

on: [push]

jobs:

  update:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - name: pip install
        run: pip install pathspec

      - name: Set author
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Pull
        run: |
          git pull --rebase
      - name: Update
        run: |
          curl -O https://raw.githubusercontent.com/thpatch/thcrap/master/scripts/utils.py
          curl -O https://raw.githubusercontent.com/thpatch/thcrap/master/scripts/repo_update.py
          python repo_update.py
      - name: Push
        run: |
          rm -r __pycache__/ repo_update.py utils.py
          git add .
          git commit -am "repo_update"
          git push
