name: repo_update

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: pip install
        run: pip install pathspec

      - name: Set user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Pull
        run: |
          git pull --rebase
      - name: Update
        run: |
          mkdir _build
          curl -L -o _build/utils.py https://raw.githubusercontent.com/thpatch/thcrap/master/scripts/utils.py
          curl -L -o _build/repo_update.py https://raw.githubusercontent.com/thpatch/thcrap/master/scripts/repo_update.py
          python _build/repo_update.py
      - name: Push
        continue-on-error: true
        run: |
          git add .
          git commit -am "repo_update"
          git push
